include: all_lint_rules.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    included_file_warning: ignore

linter:
  rules:
    always_specify_types: false
    unnecessary_final: false
    prefer_double_quotes: false
    public_member_api_docs: false
    prefer_relative_imports: false
    sort_constructors_first: false
    omit_local_variable_types: false
    prefer_asserts_with_message: false
    always_put_control_body_on_new_line: false
