name: kalman_filter
description: General purpose kalman filter implementation for dart.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  meta: ^1.2.2

dev_dependencies:
  coverage: ^0.14.2
  test: ^1.14.4
